/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employees;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import DatabaseConnection.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import sun.security.x509.AttributeNameEnumeration;
import Process.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Employ extends javax.swing.JFrame {

    Connection con;
    Statement st;
    ResultSet rs;
    Connects cn = new Connects();
    /**
     * Creates new form Employ
     */
    public static String nameRow;
    public static String staf;

    public Employ() {
        initComponents();
        this.setTitle("Employees");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        con = cn.open();
        try {
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (SQLException ex) {
            Logger.getLogger(Employ.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoadPos();
        loadTable("select Staff_ID,UserS,Pass,FullName,Birthday,Address,Mobile,Gender,a.Pos_ID,b.Pos_Name from [ComputerStore].[dbo].[Staff] a join "
                + "[ComputerStore].[dbo].[Position] b on a.Pos_ID=b.Pos_ID");
        this.edit.setEnabled(false);
        this.delete.setEnabled(false);
    }

    public void ProcessCrt(boolean b) {
        this.txtstaffid.setText("");
        this.txtaddre.setText("");
        this.txtbirth.setText("");
        this.txtmobi.setText("");
        this.txtname.setText("");
        this.txtpass.setText("");
        this.txtposid.setText("");
        this.txtuser.setText("");
    }

    public void LoadPos() {
        String sql = "select Pos_Name from Position ";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                this.box.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            Logger.getLogger(Employ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadTable(String sql) {
        rs = cn.getData(sql);
        Vector cols = new Vector();
        cols.add("StaffID");
        cols.add("User");
        cols.add("Pass");
        cols.add("Name");
        cols.add("Birthday");
        cols.add("Address");
        cols.add("Mobile");
        cols.add("Gender");
        cols.add("PosID");
        cols.add("Position");
        Vector data = new Vector();
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                Vector column = new Vector();
                column.add(rs.getInt(1));
                column.add(rs.getString(2));
                column.add(rs.getString(3));
                column.add(rs.getString(4));
                column.add(rs.getString(5));
                column.add(rs.getString(6));
                column.add(rs.getString(7));
                column.add(rs.getString(8));
                column.add(rs.getString(9));
                column.add(rs.getString(10));
                data.add(column);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employ.class.getName()).log(Level.SEVERE, null, ex);
        }
        table.setModel(new DefaultTableModel(data, cols));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtbirth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtaddre = new javax.swing.JTextField();
        txtmobi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        box = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtposid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtstaffid = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel1.setText("Name:");

        jLabel2.setText("Birthday :");

        jLabel3.setText("Address:");

        jLabel4.setText("Mobile :");

        jLabel6.setText("Pos Name");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        box.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                boxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setText("User");

        jLabel7.setText("Password");

        jLabel8.setText("Gender :");

        jLabel9.setText("Pos ID : ");

        jLabel10.setText("Staff ID :");

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addComponent(delete))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtstaffid, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtuser, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtbirth, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtaddre, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtmobi, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(gender, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtposid, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(box, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtpass))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtstaffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmobi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtposid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit)
                    .addComponent(clear))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:    
        ProcessCrt(true);
        txtpass.setEnabled(true);
        txtposid.setEnabled(true);
        add.setEnabled(true);
        edit.setEnabled(false);
        delete.setEnabled(false);        
    }//GEN-LAST:event_clearActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        txtpass.setEnabled(false);
        add.setEnabled(false);
        edit.setEnabled(true);
        delete.setEnabled(true);
        ProcessCrt(true);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        staf = model.getValueAt(table.getSelectedRow(), 0).toString();
        txtstaffid.setText(model.getValueAt(table.getSelectedRow(), 0).toString());
        txtuser.setText(model.getValueAt(table.getSelectedRow(), 1).toString());
        txtpass.setText(model.getValueAt(table.getSelectedRow(), 2).toString());
        txtname.setText(model.getValueAt(table.getSelectedRow(), 3).toString());
        txtbirth.setText(model.getValueAt(table.getSelectedRow(), 4).toString());
        txtaddre.setText(model.getValueAt(table.getSelectedRow(), 5).toString());
        txtmobi.setText(model.getValueAt(table.getSelectedRow(), 6).toString());
        gender.setSelectedItem(model.getValueAt(table.getSelectedRow(), 7).toString());
        txtposid.setText(model.getValueAt(table.getSelectedRow(), 8).toString());
        box.setSelectedItem(model.getValueAt(table.getSelectedRow(), 9).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure to delete " + staf, "Notification", 2) == 0) {
            FunctionEmployees.DeleteEm(staf);
            loadTable("select Staff_ID,UserS,Pass,FullName,Birthday,Address,Mobile,Gender,a.Pos_ID,b.Pos_Name from [ComputerStore].[dbo].[Staff] a join "
                + "[ComputerStore].[dbo].[Position] b on a.Pos_ID=b.Pos_ID");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        if (this.txtuser.getText().length() == 0 && this.txtpass.getText().length() == 0 && this.txtname.getText().length() == 0
                && this.txtbirth.getText().length() == 0 && this.txtmobi.getText().length() == 0 && this.txtmobi.getText().length() == 0
                && this.txtaddre.getText().length() == 0
                || this.txtuser.getText().length() == 0 || this.txtpass.getText().length() == 0 || this.txtname.getText().length() == 0
                || this.txtbirth.getText().length() == 0 || this.txtmobi.getText().length() == 0 || this.txtmobi.getText().length() == 0
                || this.txtaddre.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Not null", "Thông báo", 1);
        } else {
            FunctionEmployees.UpdateEm(this.txtstaffid.getText(), staf, this.txtuser.getText(), this.txtpass.getText(), this.txtname.getText(),
                    this.txtbirth.getText(), this.txtmobi.getText(), this.txtaddre.getText(), this.gender.getSelectedItem().toString(), this.txtposid.getText());
            loadTable("select Staff_ID,UserS,Pass,FullName,Birthday,Address,Mobile,Gender,a.Pos_ID,b.Pos_Name from [ComputerStore].[dbo].[Staff] a join "
                + "[ComputerStore].[dbo].[Position] b on a.Pos_ID=b.Pos_ID");
        }
    }//GEN-LAST:event_editActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if (this.txtuser.getText().length() == 0 && this.txtpass.getText().length() == 0 && this.txtname.getText().length() == 0
                && this.txtbirth.getText().length() == 0 && this.txtmobi.getText().length() == 0 && this.txtmobi.getText().length() == 0
                && this.txtaddre.getText().length() == 0
                || this.txtuser.getText().length() == 0 || this.txtpass.getText().length() == 0 || this.txtname.getText().length() == 0
                || this.txtbirth.getText().length() == 0 || this.txtmobi.getText().length() == 0 || this.txtmobi.getText().length() == 0
                || this.txtaddre.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Not null", "Thông báo", 1);
        } else {
            FunctionEmployees.InsertEm(this.txtstaffid.getText(), this.txtuser.getText(), this.txtpass.getText(), this.txtname.getText().trim(),
                    this.txtbirth.getText(), this.txtmobi.getText(), this.txtaddre.getText(), this.gender.getSelectedItem().toString(), this.txtposid.getText());
            loadTable("select Staff_ID,UserS,Pass,FullName,Birthday,Address,Mobile,Gender,a.Pos_ID,b.Pos_Name from [ComputerStore].[dbo].[Staff] a join "
                + "[ComputerStore].[dbo].[Position] b on a.Pos_ID=b.Pos_ID");
        }
    }//GEN-LAST:event_addActionPerformed

    private void boxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_boxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String sql = "select * from Position where Pos_Name=?";
        PreparedStatement pst;
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, (String) this.box.getSelectedItem());
            rs = pst.executeQuery();
            while (rs.next()) {
                this.txtposid.setText(rs.getString("Pos_ID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boxPopupMenuWillBecomeInvisible

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String st = txtsearch.getText();
        String sql;
        if (st.equals("")) {
            sql = "select Staff_ID,UserS,Pass,FullName,Birthday,Address,Mobile,Gender,a.Pos_ID,b.Pos_Name from [ComputerStore].[dbo].[Staff] a join "
                    + "[ComputerStore].[dbo].[Position] b on a.Pos_ID=b.Pos_ID";
        } else {
            sql = "select Staff_ID,UserS,Pass,FullName,Birthday,Address,Mobile,Gender,a.Pos_ID,b.Pos_Name from [ComputerStore].[dbo].[Staff] a join "
                    + "[ComputerStore].[dbo].[Position] b on a.Pos_ID=b.Pos_ID where UserS like '%" + st + "%'";
        }
        loadTable(sql);

    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> box;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtaddre;
    private javax.swing.JTextField txtbirth;
    private javax.swing.JTextField txtmobi;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtposid;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtstaffid;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
