/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

import DatabaseConnection.Connects;
import Product.Product;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Data extends javax.swing.JFrame {

    Connection con;
    Statement st;
    ResultSet rs;
    
    public static String supid = null;
    public static String groid = null;
    public static String posid = null;

    Connects cn = new Connects();

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
        this.setTitle("Database");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        con = cn.open();
        try {
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (SQLException ex) {
            Logger.getLogger(Data.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadTblGroup();
        loadTblPosition();
        loadTblSupplier();
    }

    public void ProcessCrt(boolean b) {
        this.txtSupid.setText("");
        this.txtSupName.setText("");
        this.txtSupPhone.setText("");
        this.txtGroID.setText("");
        this.txtGroName.setText("");
        this.txtposid.setText("");
        this.txtposname.setText("");
    }

    public void loadTblPosition() {
        Vector cols = new Vector();
        cols.addElement("Position ID");
        cols.addElement("Position Name");
        Vector data = new Vector();
        String sql = "select * from Position";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                Vector column = new Vector();
                column.addElement(rs.getString("Pos_ID"));
                column.addElement(rs.getString("Pos_Name"));
                data.add(column);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblPos.setModel(new DefaultTableModel(data, cols));
    }

    public void loadTblSupplier() {
        Vector cols = new Vector();
        cols.addElement("Supplier ID");
        cols.addElement("Supplier Name");
        cols.addElement("Supplier Telephone");
        Vector data = new Vector();
        String sql = "select * from Supplier";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                Vector column = new Vector();
                column.addElement(rs.getString("Sup_ID"));
                column.addElement(rs.getString("Sup_Name"));
                column.addElement(rs.getString("Sup_Telephone"));
                data.add(column);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblSupplier.setModel(new DefaultTableModel(data, cols));
    }

    public void loadTblGroup() {
        Vector cols = new Vector();
        cols.addElement("Group ID");
        cols.addElement("Group Name");
        Vector data = new Vector();
        String sql = "select * from ProGroups";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                Vector column = new Vector();
                column.addElement(rs.getString("Gro_ID"));
                column.addElement(rs.getString("Gro_Name"));
                data.add(column);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblGroup.setModel(new DefaultTableModel(data, cols));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSupid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSupName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSupPhone = new javax.swing.JTextField();
        btnAddSup = new javax.swing.JButton();
        btnDelSup = new javax.swing.JButton();
        btnEditSup = new javax.swing.JButton();
        btnClearSup = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGroup = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddGr = new javax.swing.JButton();
        btnDelGr = new javax.swing.JButton();
        btnEditGr = new javax.swing.JButton();
        btnClearGr = new javax.swing.JButton();
        txtGroID = new javax.swing.JTextField();
        txtGroName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtposid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtposname = new javax.swing.JTextField();
        btnaddPos = new javax.swing.JButton();
        btndelPos = new javax.swing.JButton();
        btneditPos = new javax.swing.JButton();
        btnclearPos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        jLabel1.setText("Supplier ID: ");

        jLabel2.setText("Supplier Name: ");

        jLabel3.setText("Supplier Telephone: ");

        btnAddSup.setText("Add");
        btnAddSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupActionPerformed(evt);
            }
        });

        btnDelSup.setText("Delete");
        btnDelSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSupActionPerformed(evt);
            }
        });

        btnEditSup.setText("Edit");
        btnEditSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSupActionPerformed(evt);
            }
        });

        btnClearSup.setText("Clear");
        btnClearSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSupid, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtSupName)
                            .addComponent(txtSupPhone))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddSup, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(btnEditSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSupid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSupPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddSup)
                            .addComponent(btnDelSup))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditSup)
                            .addComponent(btnClearSup)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supplier", jPanel1);

        tblGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGroup);

        jLabel4.setText("Group ID : ");

        jLabel5.setText("Group Name : ");

        btnAddGr.setText("Add");
        btnAddGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGrActionPerformed(evt);
            }
        });

        btnDelGr.setText("Delete");
        btnDelGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelGrActionPerformed(evt);
            }
        });

        btnEditGr.setText("Edit");
        btnEditGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGrActionPerformed(evt);
            }
        });

        btnClearGr.setText("Clear");
        btnClearGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearGrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtGroID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtGroName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddGr)
                            .addComponent(btnEditGr))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearGr)
                            .addComponent(btnDelGr))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtGroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGroName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddGr)
                            .addComponent(btnDelGr))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditGr)
                            .addComponent(btnClearGr)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Product group", jPanel2);

        tblPos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPos);

        jLabel6.setText("Position ID : ");

        jLabel7.setText("Position Name : ");

        btnaddPos.setText("Add");
        btnaddPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddPosActionPerformed(evt);
            }
        });

        btndelPos.setText("Delete");
        btndelPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelPosActionPerformed(evt);
            }
        });

        btneditPos.setText("Edit");
        btneditPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditPosActionPerformed(evt);
            }
        });

        btnclearPos.setText("Clear");
        btnclearPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearPosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnaddPos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneditPos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndelPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnclearPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtposid, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtposname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtposid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtposname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnaddPos)
                            .addComponent(btndelPos))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneditPos)
                            .addComponent(btnclearPos))))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Position", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSupActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure to delete " + supid, "Notification", 2) == 0) {
            FunctionData.DeleteSup(supid);
            loadTblSupplier();
        }
    }//GEN-LAST:event_btnDelSupActionPerformed

    private void btnClearSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSupActionPerformed
        // TODO add your handling code here:
        ProcessCrt(true);
    }//GEN-LAST:event_btnClearSupActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblSupplier.getModel();
        supid = model.getValueAt(tblSupplier.getSelectedRow(), 0).toString();
        txtSupid.setText(model.getValueAt(tblSupplier.getSelectedRow(), 0).toString());
        txtSupName.setText(model.getValueAt(tblSupplier.getSelectedRow(), 1).toString());
        txtSupPhone.setText(model.getValueAt(tblSupplier.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void tblGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblGroup.getModel();
        groid = model.getValueAt(tblGroup.getSelectedRow(), 0).toString();
        txtGroID.setText(model.getValueAt(tblGroup.getSelectedRow(), 0).toString());
        txtGroName.setText(model.getValueAt(tblGroup.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tblGroupMouseClicked

    private void btnClearGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearGrActionPerformed
        // TODO add your handling code here:
        ProcessCrt(true);
    }//GEN-LAST:event_btnClearGrActionPerformed

    private void btnAddSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupActionPerformed
        // TODO add your handling code here:
        if (this.txtSupid.getText().length() == 0 && this.txtSupName.getText().length() == 0 && this.txtSupPhone.getText().length() == 0
                || this.txtSupid.getText().length() == 0 || this.txtSupName.getText().length() == 0 || this.txtSupPhone.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Not null", "Thông báo", 1);
        } else {
            FunctionData.InsertSup(this.txtSupid.getText(), this.txtSupName.getText(), this.txtSupPhone.getText());
            loadTblSupplier();
        }
    }//GEN-LAST:event_btnAddSupActionPerformed

    private void btnEditSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSupActionPerformed
        // TODO add your handling code here:
        if (this.txtSupid.getText().length() == 0 && this.txtSupName.getText().length() == 0 && this.txtSupPhone.getText().length() == 0
                || this.txtSupid.getText().length() == 0 || this.txtSupName.getText().length() == 0 || this.txtSupPhone.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Not null", "Thông báo", 1);
        } else {
            FunctionData.UpdateSup(supid, this.txtSupid.getText(), this.txtSupName.getText(), this.txtSupPhone.getText());
            loadTblSupplier();
        }
    }//GEN-LAST:event_btnEditSupActionPerformed

    private void btnAddGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGrActionPerformed
        // TODO add your handling code here:
        if (this.txtGroID.getText().length() == 0 && this.txtGroName.getText().length() == 0
                || this.txtGroID.getText().length() == 0 || this.txtGroName.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Not null", "Thông báo", 1);
        } else {
            FunctionData.InsertGro(this.txtGroID.getText(), this.txtGroName.getText());
            loadTblGroup();
        }
    }//GEN-LAST:event_btnAddGrActionPerformed

    private void btnDelGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelGrActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure to delete " + groid, "Notification", 2) == 0) {
            FunctionData.DeleteGro(groid);
            loadTblGroup();
        }
    }//GEN-LAST:event_btnDelGrActionPerformed

    private void btnEditGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGrActionPerformed
        // TODO add your handling code here:
        if (this.txtGroID.getText().length() == 0 && this.txtGroName.getText().length() == 0
                || this.txtGroID.getText().length() == 0 || this.txtGroName.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Not null", "Thông báo", 1);
        } else {
            FunctionData.UpdateGro(groid, this.txtGroID.getText(), this.txtGroName.getText());
            loadTblGroup();
        }
    }//GEN-LAST:event_btnEditGrActionPerformed

    private void btnclearPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearPosActionPerformed
        // TODO add your handling code here:
        ProcessCrt(true);
    }//GEN-LAST:event_btnclearPosActionPerformed

    private void btnaddPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddPosActionPerformed
        // TODO add your handling code here:
        if (this.txtposid.getText().length() == 0 && this.txtposname.getText().length() == 0
                || this.txtposid.getText().length() == 0 || this.txtposname.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Not null", "Thông báo", 1);
        } else {
            FunctionData.InsertPos(this.txtposid.getText(), this.txtposname.getText());
            loadTblPosition();
        }
    }//GEN-LAST:event_btnaddPosActionPerformed

    private void btndelPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelPosActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure to delete " + posid, "Notification", 2) == 0) {
            FunctionData.DeletePos(posid);
            loadTblPosition();
        }
    }//GEN-LAST:event_btndelPosActionPerformed

    private void btneditPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditPosActionPerformed
        // TODO add your handling code here:
        if (this.txtposid.getText().length() == 0 && this.txtposname.getText().length() == 0
                || this.txtposid.getText().length() == 0 || this.txtposname.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Not null", "Thông báo", 1);
        } else {
            FunctionData.UpdatePos(posid, this.txtposid.getText(), this.txtposname.getText());
            loadTblPosition();
        }
    }//GEN-LAST:event_btneditPosActionPerformed

    private void tblPosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPosMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPos.getModel();
        posid = model.getValueAt(tblPos.getSelectedRow(), 0).toString();
        txtposid.setText(model.getValueAt(tblPos.getSelectedRow(), 0).toString());
        txtposname.setText(model.getValueAt(tblPos.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tblPosMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGr;
    private javax.swing.JButton btnAddSup;
    private javax.swing.JButton btnClearGr;
    private javax.swing.JButton btnClearSup;
    private javax.swing.JButton btnDelGr;
    private javax.swing.JButton btnDelSup;
    private javax.swing.JButton btnEditGr;
    private javax.swing.JButton btnEditSup;
    private javax.swing.JButton btnaddPos;
    private javax.swing.JButton btnclearPos;
    private javax.swing.JButton btndelPos;
    private javax.swing.JButton btneditPos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblGroup;
    private javax.swing.JTable tblPos;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtGroID;
    private javax.swing.JTextField txtGroName;
    private javax.swing.JTextField txtSupName;
    private javax.swing.JTextField txtSupPhone;
    private javax.swing.JTextField txtSupid;
    private javax.swing.JTextField txtposid;
    private javax.swing.JTextField txtposname;
    // End of variables declaration//GEN-END:variables
}
