/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Account.*;
import Database.Data;
import Employees.*;
import Order.Order;
import Product.*;
/**
 *
 * @author Admin
 */
public class AdminForm extends javax.swing.JFrame {

    static Boolean loggedIn=false;
    /**
     * Creates new form MainForm
     */
    public AdminForm() {
        initComponents();        
    }

    public void setname(String s){
        lbname2.setText(s);
    }
    
    public String getname(){
        return lbname2.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmploy = new javax.swing.JButton();
        btnProdu = new javax.swing.JButton();
        btnAcc = new javax.swing.JButton();
        btnData = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnorder = new javax.swing.JButton();
        lbname = new javax.swing.JLabel();
        lbname2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        changepass = new javax.swing.JMenuItem();
        jmiOut = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEmploy.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnEmploy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Groups-Meeting-Dark-icon.png"))); // NOI18N
        btnEmploy.setText("EMPLOYEES");
        btnEmploy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmploy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmploy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployActionPerformed(evt);
            }
        });

        btnProdu.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnProdu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shopping-bag-icon.png"))); // NOI18N
        btnProdu.setText("PRODUCT");
        btnProdu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProdu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduActionPerformed(evt);
            }
        });

        btnAcc.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Apps-preferences-desktop-user-password-icon.png"))); // NOI18N
        btnAcc.setText("ACCOUNT");
        btnAcc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccActionPerformed(evt);
            }
        });

        btnData.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/web_database2.png"))); // NOI18N
        btnData.setText("DATABASE");
        btnData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("PLEASE SELECT THE FUNCTION");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnorder.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/basket-icon.png"))); // NOI18N
        btnorder.setText("ORDER");
        btnorder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnorder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });

        lbname.setText("Hello : ");

        jMenu1.setText("Systems");

        changepass.setText("Change Password");
        changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassActionPerformed(evt);
            }
        });
        jMenu1.add(changepass);

        jmiOut.setText("LogOut");
        jmiOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOutActionPerformed(evt);
            }
        });
        jMenu1.add(jmiOut);

        jMenuItem1.setText("Exit Application");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEmploy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProdu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAcc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnorder, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbname2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbname)
                    .addComponent(lbname2))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator3)
                    .addComponent(btnData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(btnAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmploy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator4)
                    .addComponent(btnorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployActionPerformed
        // TODO add your handling code here:
        Employ em=new Employ();
        em.setVisible(true);
    }//GEN-LAST:event_btnEmployActionPerformed

    private void btnProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduActionPerformed
        // TODO add your handling code here:
        Product pr=new Product();
        pr.setVisible(true);
    }//GEN-LAST:event_btnProduActionPerformed

    private void btnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActionPerformed
        // TODO add your handling code here:
        Data d=new Data();
        d.setVisible(true);
    }//GEN-LAST:event_btnDataActionPerformed

    private void btnAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccActionPerformed
        // TODO add your handling code here:
        Account acc=new Account();
        acc.setVisible(true);
    }//GEN-LAST:event_btnAccActionPerformed

    private void jmiOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOutActionPerformed
        // TODO add your handling code here:
        loggedIn=false;
        this.dispose();
        LoginForm lf=new LoginForm();
        lf.show();
    }//GEN-LAST:event_jmiOutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassActionPerformed
        // TODO add your handling code here:
        ChangePassword cp=new ChangePassword();
        cp.setVisible(true);
        cp.setuser(this.lbname2.getText());
    }//GEN-LAST:event_changepassActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        // TODO add your handling code here:
        Order or=new Order();
        or.setVisible(true);
        
    }//GEN-LAST:event_btnorderActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcc;
    private javax.swing.JButton btnData;
    private javax.swing.JButton btnEmploy;
    private javax.swing.JButton btnProdu;
    private javax.swing.JButton btnorder;
    private javax.swing.JMenuItem changepass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenuItem jmiOut;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbname2;
    // End of variables declaration//GEN-END:variables
}
